remapcaps &
xset r rate 300 45 &
xdotool key Num_Lock &
redshift -O 2600 &
xrdb .config/x11/.Xresources
setbg &
dunst &
randomTheme &
# xinput --set-prop 15 "libinput Natural Scrolling Enabled" 1

while true; do
    ssh-agent dwm >/dev/null 2>&1
done
