dunst &
remaps &
dwmblocks &
randomTheme &
redshift -O 2600 &
xrdb .config/x11/.Xresources
xwallpaper --zoom /mnt/Seagate/wallpapers/Anime/spider-verse.png &

/* setbg & */
/* compton & */

while true; do
    ssh-agent dwm || break
done
