remaps &
setbg &
dunst &
redshift -O 2600 &
compton &
xrdb .config/x11/.Xresources
randomTheme &

# reverse scroll
# xinput --set-prop 15 "libinput Natural Scrolling Enabled" 1

while ;; do
    ssh-agent dwm || break
done
