[v1]
"aoc-cli 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["aoc"]
"atuin 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["atuin"]
"bacon 2.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"binserve 0.2.0 (git+https://github.com/mufeedvh/binserve.git#ed5fe0773cd1314cfd5223f603b4cf18bd7bfec2)" = ["binserve"]
"bottom 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"broot 1.20.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"cargo-bloat 0.11.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-edit 0.11.9 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-pkgbuild 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-pkgbuild"]
"cargo-script 0.2.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-script",
    "run-cargo-script",
]
"cargo-update 11.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-watch 8.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"cargocleaner 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargocleaner"]
"cbfmt 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cbfmt"]
"chars 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["chars"]
"checkpwn 0.5.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["checkpwn"]
"clock-tui 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tclock"]
"cpc 1.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cpc"]
"csview 1.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["csview"]
"ctrlg 0.9.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ctrlg"]
"ddh 0.12.0 (git+https://github.com/darakian/ddh#f54ba5d6f8cf96a641808771b0c33f9a871918c3)" = ["ddh"]
"devmode 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dm"]
"dijo 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["dijo"]
"diskonaut 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskonaut"]
"dotter 0.12.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["dotter"]
"dua-cli 2.19.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["dua"]
"dufs 0.32.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dufs"]
"dune 0.1.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["dunesh"]
"eva 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["eva"]
"fcp 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fcp"]
"fend 1.1.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["fend"]
"ffsend 0.2.76 (registry+https://github.com/rust-lang/crates.io-index)" = ["ffsend"]
"flamegraph 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"gifski 1.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["gifski"]
"git-cliff 1.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"git-grab 1.0.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-grab"]
"git-journal 1.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["git-journal"]
"grex 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"grup 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["grup"]
"hoard-rs 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["hoard"]
"htmlq 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["htmlq"]
"https 1.12.5 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "http",
    "httplz",
]
"huniq 2.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["huniq"]
"hwatch 0.3.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["hwatch"]
"hx 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"hyperfine 1.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"image-roll 2.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["image-roll"]
"imdl 0.1.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["imdl"]
"jaq 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jaq"]
"joshuto 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["joshuto"]
"just 1.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"kalker 2.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["kalker"]
"lemmeknow 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lemmeknow"]
"lfs 2.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lfs"]
"lscolors 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lscolors"]
"mdbook 0.4.27 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"mdbook-catppuccin 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook-catppuccin"]
"miniserve 0.22.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["miniserve"]
"muc 0.1.0 (git+https://github.com/nate-sys/muc#d651dcf907780086601edb29b9555971dfe20757)" = ["muc"]
"navi 2.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["navi"]
"nomino 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["nomino"]
"oha 0.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["oha"]
"ouch 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["ouch"]
"paru 1.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["paru"]
"parui 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["parui"]
"pipe-rename 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["renamer"]
"pipr 0.0.16 (registry+https://github.com/rust-lang/crates.io-index)" = ["pipr"]
"projclean 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["projclean"]
"rathole 0.4.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["rathole"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rnr 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr"]
"rustlings 5.2.1 (path+file:///home/jedi/workspace/github.com/rust-lang/rustlings)" = ["rustlings"]
"rusty-krab-manager 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-krab-manager"]
"rusty-tags 3.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rusty-tags"]
"sccache 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["sccache"]
"sd 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"silicon 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["silicon"]
"skim 0.10.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"smokey 0.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["smokey"]
"sniffnet 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["sniffnet"]
"so 0.4.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["so"]
"stringsext 2.3.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["stringsext"]
"systeroid 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["systeroid"]
"szyszka 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["szyszka"]
"t-rec 0.7.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["t-rec"]
"termchat 1.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["termchat"]
"termscp 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["termscp"]
"termusic 0.7.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["termusic"]
"thokr 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["thokr"]
"tickrs 0.14.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["tickrs"]
"toipe 0.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "randomword",
    "toipe",
]
"tuc 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tuc"]
"tuifeed 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tuifeed"]
"tunnelto 0.1.19 (registry+https://github.com/rust-lang/crates.io-index)" = ["tunnelto"]
"xcp 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"xxv 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["xxv"]
