version: "3"
volumes:
  nextcloud:
  nextcloud-db:
networks:
  frontend:
    name: proxy
  backend:
services:
  nextcloud-app:
    image: nextcloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=Jedi@falcon1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      - frontend
      - backend
  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Jedi@falcon1
      - MYSQL_PASSWORD=Jedi@falcon1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
