#!/usr/bin/env bash

#!/usr/bin/bash

set -o nounset    # error when referencing undefined variable
set -o errexit    # exit when command fails

# Install extensions
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
if [ ! -f package.json ]
then
  echo '{"dependencies":{}}'> package.json
fi
# Change extension names to the extensions you need
npm install coc-snippets coc-python coc-html coc-css coc-json coc-yaml coc-discord-neovim coc-prettier coc-marketplace coc-lua coc-explorer coc-java coc-java coc-go coc-xml coc-java-debug coc-vimlsp coc-sh coc-sql coc-markdownlint --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
