#!/usr/bin/env bash

list=$(transmission-remote -t all -i | grep "Name:\|Have:\|Total size:" | sed "s/.*Name://g; s/.*Have:/Downloaded:/; s/.*Total size:/Total:/" | sed "/^\s*Total/a \ ")
notify-send "Torrents" "$list"
