#!/usr/bin/env bash

filename=$1

# Exit if filename is not specified
[ -z $filename ] && echo "Filename not specified" && exit 1

cd "$HOME/scripts"
touch "$filename"
chmod +x "$filename"
echo "#!/usr/bin/env bash" > "$filename"
