#!/usr/bin/env bash

dirname="/mnt/Seagate/Wallpapers/desktop"
file=$(ls -A "$dirname" | shuf -n 1)

if [[ -d "$dirname/$file" ]]; then
  file="$file/$(ls -A "$dirname"/"$file" | shuf -n 1)"
fi

xwallpaper --zoom "$dirname"/"$file"
