#!/usr/bin/env bash

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon" && sleep 2)

transmission-remote -a "$@" && notify-send "Transmission daemon" "🔽 Torrent added."
