general.import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[cursor]
unfocused_hollow = true

[scrolling]
history = 2000

[font]
size = 9
bold = { family = "monospace", style = "Heavy" }
normal = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }

[keyboard]
bindings = [
	{ mods = "Control|Shift", key = "Q", action = "Quit" },
	{ mods = "Control|Shift", key = "C", action = "Copy" },
	{ mods = "Control|Shift", key = "V", action = "Paste" },
	{ mods = "Control|Shift", key = "N", action = "SpawnNewInstance" },
]

[window]
title = "Alacritty"
padding = { x = 6, y = 6 }
class = { general = "Alacritty", instance = "Alacritty" }
